#
# Makefile for the nubia drivers.
#

obj-$(CONFIG_NUBIA_TOUCHSCREENS)      += touch/
obj-$(CONFIG_NUBIA_NFC)	         += nfc/
obj-$(CONFIG_NUBIA_DISPLAY)      += display/
obj-$(CONFIG_NUBIA_SENSORS)	     +=sensors/
obj-y      += fingerprint/
